spring.application.name=fyp-backend

spring.datasource.url=jdbc:mysql://localhost:3306/fyp
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
app.jwt.secret=9a3a9b1c7d2e5f8g4h6j8k9l2m3n5p7q9r1s3t5v7w8x2y4z6b8c9d1e3f5g7h9j2k4m6n8p
app.jwt.expiration-ms=86400000

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173

# Mail Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aakashsah438@gmail.com
spring.mail.password=aaywsmoblfgweiao
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
